# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ganrqunx/Git/fcitx-table-dayi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ganrqunx/Git/fcitx-table-dayi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ganrqunx/Git/fcitx-table-dayi/CMakeFiles /home/ganrqunx/Git/fcitx-table-dayi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ganrqunx/Git/fcitx-table-dayi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-5

# Build rule for target.
fcitx-addon-translation-handler-5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-5
.PHONY : fcitx-addon-translation-handler-5

# fast build rule for target.
fcitx-addon-translation-handler-5/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-5.dir/build.make CMakeFiles/fcitx-addon-translation-handler-5.dir/build
.PHONY : fcitx-addon-translation-handler-5/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-4

# Build rule for target.
fcitx-addon-translation-handler-4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-4
.PHONY : fcitx-addon-translation-handler-4

# fast build rule for target.
fcitx-addon-translation-handler-4/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-4.dir/build.make CMakeFiles/fcitx-addon-translation-handler-4.dir/build
.PHONY : fcitx-addon-translation-handler-4/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-3

# Build rule for target.
fcitx-addon-translation-handler-3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-3
.PHONY : fcitx-addon-translation-handler-3

# fast build rule for target.
fcitx-addon-translation-handler-3/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-3.dir/build.make CMakeFiles/fcitx-addon-translation-handler-3.dir/build
.PHONY : fcitx-addon-translation-handler-3/fast

#=============================================================================
# Target rules for targets named fcitx-extract-traslation.dependency

# Build rule for target.
fcitx-extract-traslation.dependency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-extract-traslation.dependency
.PHONY : fcitx-extract-traslation.dependency

# fast build rule for target.
fcitx-extract-traslation.dependency/fast:
	$(MAKE) -f CMakeFiles/fcitx-extract-traslation.dependency.dir/build.make CMakeFiles/fcitx-extract-traslation.dependency.dir/build
.PHONY : fcitx-extract-traslation.dependency/fast

#=============================================================================
# Target rules for targets named fcitx-modules.target

# Build rule for target.
fcitx-modules.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-modules.target
.PHONY : fcitx-modules.target

# fast build rule for target.
fcitx-modules.target/fast:
	$(MAKE) -f CMakeFiles/fcitx-modules.target.dir/build.make CMakeFiles/fcitx-modules.target.dir/build
.PHONY : fcitx-modules.target/fast

#=============================================================================
# Target rules for targets named fcitx-parse-pos.dependency

# Build rule for target.
fcitx-parse-pos.dependency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-parse-pos.dependency
.PHONY : fcitx-parse-pos.dependency

# fast build rule for target.
fcitx-parse-pos.dependency/fast:
	$(MAKE) -f CMakeFiles/fcitx-parse-pos.dependency.dir/build.make CMakeFiles/fcitx-parse-pos.dependency.dir/build
.PHONY : fcitx-parse-pos.dependency/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-6

# Build rule for target.
fcitx-addon-translation-handler-6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-6
.PHONY : fcitx-addon-translation-handler-6

# fast build rule for target.
fcitx-addon-translation-handler-6/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-6.dir/build.make CMakeFiles/fcitx-addon-translation-handler-6.dir/build
.PHONY : fcitx-addon-translation-handler-6/fast

#=============================================================================
# Target rules for targets named fcitx-scan-addons.target

# Build rule for target.
fcitx-scan-addons.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-scan-addons.target
.PHONY : fcitx-scan-addons.target

# fast build rule for target.
fcitx-scan-addons.target/fast:
	$(MAKE) -f CMakeFiles/fcitx-scan-addons.target.dir/build.make CMakeFiles/fcitx-scan-addons.target.dir/build
.PHONY : fcitx-scan-addons.target/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-2

# Build rule for target.
fcitx-addon-translation-handler-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-2
.PHONY : fcitx-addon-translation-handler-2

# fast build rule for target.
fcitx-addon-translation-handler-2/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-2.dir/build.make CMakeFiles/fcitx-addon-translation-handler-2.dir/build
.PHONY : fcitx-addon-translation-handler-2/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-1

# Build rule for target.
fcitx-addon-translation-handler-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-1
.PHONY : fcitx-addon-translation-handler-1

# fast build rule for target.
fcitx-addon-translation-handler-1/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-1.dir/build.make CMakeFiles/fcitx-addon-translation-handler-1.dir/build
.PHONY : fcitx-addon-translation-handler-1/fast

#=============================================================================
# Target rules for targets named pot

# Build rule for target.
pot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pot
.PHONY : pot

# fast build rule for target.
pot/fast:
	$(MAKE) -f po/CMakeFiles/pot.dir/build.make po/CMakeFiles/pot.dir/build
.PHONY : pot/fast

#=============================================================================
# Target rules for targets named fcitx-compile-mo.target

# Build rule for target.
fcitx-compile-mo.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-compile-mo.target
.PHONY : fcitx-compile-mo.target

# fast build rule for target.
fcitx-compile-mo.target/fast:
	$(MAKE) -f po/CMakeFiles/fcitx-compile-mo.target.dir/build.make po/CMakeFiles/fcitx-compile-mo.target.dir/build
.PHONY : fcitx-compile-mo.target/fast

#=============================================================================
# Target rules for targets named fcitx-translate-pot.target

# Build rule for target.
fcitx-translate-pot.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-translate-pot.target
.PHONY : fcitx-translate-pot.target

# fast build rule for target.
fcitx-translate-pot.target/fast:
	$(MAKE) -f po/CMakeFiles/fcitx-translate-pot.target.dir/build.make po/CMakeFiles/fcitx-translate-pot.target.dir/build
.PHONY : fcitx-translate-pot.target/fast

#=============================================================================
# Target rules for targets named fcitx-parse-pos.target

# Build rule for target.
fcitx-parse-pos.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-parse-pos.target
.PHONY : fcitx-parse-pos.target

# fast build rule for target.
fcitx-parse-pos.target/fast:
	$(MAKE) -f po/CMakeFiles/fcitx-parse-pos.target.dir/build.make po/CMakeFiles/fcitx-parse-pos.target.dir/build
.PHONY : fcitx-parse-pos.target/fast

#=============================================================================
# Target rules for targets named fcitx-addon-apply-translation-1

# Build rule for target.
fcitx-addon-apply-translation-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-apply-translation-1
.PHONY : fcitx-addon-apply-translation-1

# fast build rule for target.
fcitx-addon-apply-translation-1/fast:
	$(MAKE) -f tables/CMakeFiles/fcitx-addon-apply-translation-1.dir/build.make tables/CMakeFiles/fcitx-addon-apply-translation-1.dir/build
.PHONY : fcitx-addon-apply-translation-1/fast

#=============================================================================
# Target rules for targets named table_data

# Build rule for target.
table_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 table_data
.PHONY : table_data

# fast build rule for target.
table_data/fast:
	$(MAKE) -f tables/CMakeFiles/table_data.dir/build.make tables/CMakeFiles/table_data.dir/build
.PHONY : table_data/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... uninstall"
	@echo "... fcitx-addon-translation-handler-5"
	@echo "... fcitx-addon-translation-handler-4"
	@echo "... edit_cache"
	@echo "... fcitx-addon-translation-handler-3"
	@echo "... rebuild_cache"
	@echo "... fcitx-extract-traslation.dependency"
	@echo "... fcitx-modules.target"
	@echo "... fcitx-parse-pos.dependency"
	@echo "... install"
	@echo "... fcitx-addon-translation-handler-6"
	@echo "... fcitx-scan-addons.target"
	@echo "... fcitx-addon-translation-handler-2"
	@echo "... install/local"
	@echo "... fcitx-addon-translation-handler-1"
	@echo "... pot"
	@echo "... fcitx-compile-mo.target"
	@echo "... fcitx-translate-pot.target"
	@echo "... fcitx-parse-pos.target"
	@echo "... fcitx-addon-apply-translation-1"
	@echo "... table_data"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

